#!/usr/bin/env python3
"""Bundle every PNG in assets/sprites and assets/custom into src/assets.js as
base64 data URIs, so the game runs from file:// and can be inlined into a
single-file build by tools/build_dist.py."""
import base64
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "src", "assets.js")

entries = []
for sub in ("assets/sprites", "assets/custom", "assets/craftpix"):
    d = os.path.join(ROOT, sub)
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".png"):
            continue
        name = fn[:-4].replace("_anim_f", "_f")
        with open(os.path.join(d, fn), "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        entries.append(f'  "{name}": "data:image/png;base64,{b64}"')

with open(os.path.join(ROOT, "assets", "credits.json")) as f:
    credits = json.load(f)

with open(OUT, "w") as f:
    f.write("// generated by tools/build_assets.py — do not edit\n")
    f.write("window.ASSETS = {\n" + ",\n".join(entries) + "\n};\n")
    f.write("// source of truth: assets/credits.json\n")
    f.write("window.CREDITS = " + json.dumps(credits, indent=1) + ";\n")
print(f"wrote {OUT} with {len(entries)} sprites + credits")
