#!/usr/bin/env python3
"""Generate the original pixel-art sprites for Orc Slasher (campfire, gems,
effects, the Orc Warchief boss and berserker recolors). Output: assets/custom/.

All art here is hand-authored in-code (CC0, do whatever you want with it)."""
import colorsys
import os
import random
from PIL import Image

OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "custom")
SPRITES = os.path.join(os.path.dirname(__file__), "..", "assets", "sprites")
os.makedirs(OUT, exist_ok=True)


def save_grid(name, grid, palette):
    rows = [r for r in grid.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    img = Image.new("RGBA", (w, len(rows)), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch in palette:
                px[x, y] = palette[ch]
    img.save(os.path.join(OUT, name + ".png"))
    return img


# ---------------------------------------------------------------- campfire --
FIRE_PAL = {
    "K": (34, 24, 26, 255),    # log outline
    "L": (92, 62, 40, 255),    # log
    "l": (128, 90, 56, 255),   # log light
    "S": (60, 56, 64, 255),    # stone
    "s": (90, 86, 96, 255),    # stone light
    "R": (206, 66, 28, 255),   # flame red
    "O": (238, 130, 32, 255),  # flame orange
    "Y": (252, 210, 96, 255),  # flame yellow
    "W": (255, 246, 200, 255), # flame core
}

CAMPFIRE = [
"""
................
................
................
......R.R.......
.....RORRO......
....ROYYOOR.....
....ROYWYOR.....
.....OYWWYO.....
.....ROYYOR.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
......R..R......
.....R.RR.......
.....RROORR.....
....ROYOYOR.....
.....OYWYYO.....
....ROYWWYOR....
.....OYYYYO.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
................
.......RR.......
......ROOR......
.....ROYYOR.....
....ROYWWYOR....
....ROYWWYOR....
.....OYWYYO.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
.....R..........
......RR..R.....
.....RORRRO.....
.....ROYYOR.....
....ROYWYOOR....
.....OYWWYO.....
.....ROYYOR.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
]
for i, g in enumerate(CAMPFIRE):
    save_grid(f"campfire_f{i}", g, FIRE_PAL)

# ---------------------------------------------------------------- xp gem ----
GEM_PAL = {
    "K": (20, 40, 24, 255),
    "G": (52, 168, 83, 255),
    "g": (30, 110, 54, 255),
    "W": (198, 255, 208, 255),
}
save_grid("xp_gem_f0", """
...KK...
..KGGK..
.KGWGGK.
.KGGGgK.
.KGGggK.
..KggK..
...KK...
""", GEM_PAL)
save_grid("xp_gem_f1", """
...KK...
..KWGK..
.KGGGGK.
.KGGGgK.
.KWGggK.
..KggK..
...KK...
""", GEM_PAL)

# ------------------------------------------------------------ shaman bolt ---
BOLT_PAL = {
    "G": (86, 224, 90, 255),
    "g": (34, 140, 60, 190),
    "W": (222, 255, 200, 255),
}
save_grid("shaman_bolt_f0", """
..gg..
.gGGg.
gGWWGg
gGWWGg
.gGGg.
..gg..
""", BOLT_PAL)
save_grid("shaman_bolt_f1", """
..gg..
.gGGg.
gGGWGg
gGWGGg
.gGGg.
..gg..
""", BOLT_PAL)

# ------------------------------------------------------------ slash arc -----
SLASH_PAL = {
    "W": (255, 255, 255, 235),
    "S": (188, 210, 232, 200),
    "s": (130, 158, 190, 120),
}
save_grid("slash_f0", """
................
............ss..
..........sSSs..
........sSSWs...
......sSWWs.....
....sSWWs.......
...sSWs.........
...sWs..........
...ss...........
................
""", SLASH_PAL)
save_grid("slash_f1", """
................
...........ss...
.........sSWWs..
.......sSWWWs...
.....sSWWWs.....
...sSWWWs.......
..sSWWs.........
..sWWs..........
..sss...........
................
""", SLASH_PAL)
save_grid("slash_f2", """
................
..........s.....
........sSs.....
......sSSs......
....sSSs........
...sSs..........
..ss............
..s.............
................
................
""", SLASH_PAL)

# ------------------------------------------------------- orc warchief boss --
# Original 18x26 hulking orc: iron pauldrons, gold-trimmed helm horns,
# red warpaint, glowing eyes, big tusks.
WCH_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "G": (110, 152, 62, 255),  # skin
    "g": (74, 106, 46, 255),   # skin shade
    "D": (46, 36, 34, 255),    # hair / dark leather
    "W": (240, 236, 220, 255), # tusk / teeth
    "R": (255, 64, 48, 255),   # glowing eyes
    "P": (182, 40, 46, 255),   # warpaint / banner cloth
    "A": (118, 116, 130, 255), # iron
    "a": (74, 72, 88, 255),    # iron shade
    "Y": (226, 180, 62, 255),  # gold trim
    "B": (82, 58, 44, 255),    # pants
    "b": (52, 40, 34, 255),    # boots
}

WCH_TOP = """
....KK......KK....
...KYYK....KYYK...
...KYAYK..KYAYK...
....KAAK..KAAK....
....KAAAKKAAAK....
.....KAAAAAAK.....
.....KAaaaaAK.....
....KGGGGGGGGK....
....KGPGGGGPGK....
...KGGRGGGGRGGK...
...KGGGGggGGGGK...
...KGWGgggGGWGK...
....KWGGGGGGWK....
.....KGWWWWGK.....
..KAAKKGGGGKKAAK..
.KAaaAKKKKKKAaaAK.
.KAaaAKPGGPKAaaAK.
.KKAAKKGGGGKKAAKK.
..KgK.KgGGgK.KgK..
..KgK.KGGGGK.KgK..
""".strip("\n")

WCH_LEGS_STAND = """
......KBBBBK......
......KB..BK......
......KbK.KbK.....
.....KbbK.KbbK....
......KK...KK.....
""".strip("\n")

WCH_LEGS_A = """
......KBBBBK......
.....KBK..KBK.....
....KbbK...KbK....
....KbbK..KbbK....
.....KK....KK.....
""".strip("\n")

WCH_LEGS_B = """
......KBBBBK......
.....KBK..KBK.....
....KbK...KbbK....
....KbbK..KbbK....
.....KK....KK.....
""".strip("\n")


def warchief(name, legs, bob):
    body = ("." * 18 + "\n") * bob + WCH_TOP + "\n" + legs
    save_grid(name, body, WCH_PAL)


warchief("orc_warchief_idle_f0", WCH_LEGS_STAND, 1)
warchief("orc_warchief_idle_f1", WCH_LEGS_STAND, 0)
warchief("orc_warchief_idle_f2", WCH_LEGS_STAND, 0)
warchief("orc_warchief_idle_f3", WCH_LEGS_STAND, 1)
warchief("orc_warchief_run_f0", WCH_LEGS_A, 1)
warchief("orc_warchief_run_f1", WCH_LEGS_STAND, 0)
warchief("orc_warchief_run_f2", WCH_LEGS_B, 1)
warchief("orc_warchief_run_f3", WCH_LEGS_STAND, 0)

# ------------------------------------------------------ cave goblin --------
# pale swarm goblin: 0x72 goblin recolored toward cave-blind blue-grey.


def recolor_goblin(src, dst):
    img = Image.open(src).convert("RGBA")
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            if a and g > r * 1.05 and g > 60:  # green skin
                h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
                r2, g2, b2 = colorsys.hls_to_rgb(0.52, min(1, l * 1.25), s * 0.45)
                px[x, y] = (int(r2 * 255), int(g2 * 255), int(b2 * 255), a)
    img.save(dst)


for anim in ("idle", "run"):
    for f in range(4):
        recolor_goblin(
            os.path.join(SPRITES, f"goblin_{anim}_anim_f{f}.png"),
            os.path.join(OUT, f"cave_goblin_{anim}_f{f}.png"),
        )

# ---------------------------------------------------- orc soulcaller boss --
# summons the ghosts of fallen orcs: spectral skin, tattered robe, skull staff.
SOU_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "G": (152, 192, 162, 255), # spectral skin
    "g": (104, 142, 118, 255), # skin shade
    "D": (42, 52, 56, 255),    # robe
    "d": (60, 74, 78, 255),    # robe light
    "E": (120, 255, 220, 255), # glowing eyes / wisps
    "T": (238, 234, 220, 255), # tusks
    "S": (222, 216, 196, 255), # bone staff
    "s": (176, 168, 148, 255), # staff shade
    "W": (245, 242, 230, 255), # staff skull
}

SOU_TOP = """
..E...KKKKKK...E..
.....KDDDDDDK.....
....KDDDDDDDDK....
....KDGGGGGGDK.KK.
....KDGEGGEGDKKWWK
....KDGGGGGGDKWWWK
....KDTGGGTGDKKWK.
.....KGTTTGGK.KsK.
....KDDDDDDDDKKSK.
...KDDDDDDDDDDKSK.
..KDdDDDDDDdDKKSK.
..KGKDDDDDDKGKKSK.
..KGKdDDDDdKGKKsK.
..KKKdDDDDdKKKKSK.
....KdDDDDdK..KsK.
....KDDDDDDK..KSK.
...KDDDDDDDDK.KK..
""".strip("\n")

SOU_LEGS_STAND = """
...KdDDDDDDdK.....
....KKKKKKKK......
""".strip("\n")


def soulcaller(name, bob):
    save_grid(name, ("." * 18 + "\n") * bob + SOU_TOP + "\n" + SOU_LEGS_STAND, SOU_PAL)


soulcaller("orc_soulcaller_idle_f0", 1)
soulcaller("orc_soulcaller_idle_f1", 0)
soulcaller("orc_soulcaller_idle_f2", 0)
soulcaller("orc_soulcaller_idle_f3", 1)
soulcaller("orc_soulcaller_run_f0", 1)
soulcaller("orc_soulcaller_run_f1", 0)
soulcaller("orc_soulcaller_run_f2", 1)
soulcaller("orc_soulcaller_run_f3", 0)

# ------------------------------------------------- grommok, the orc god ----
# wave-20 boss: crimson demi-god, obsidian pauldrons, horned iron crown,
# lava veins glowing through the skin.
GOD_PAL = {
    "K": (20, 14, 22, 255),    # outline
    "R": (158, 54, 44, 255),   # crimson skin
    "r": (112, 38, 32, 255),   # skin shade
    "L": (255, 140, 40, 255),  # lava veins
    "E": (255, 190, 60, 255),  # burning eyes
    "A": (58, 52, 66, 255),    # obsidian armor
    "a": (38, 34, 46, 255),    # armor shade
    "Y": (226, 180, 62, 255),  # gold crown band
    "T": (240, 236, 220, 255), # tusks
    "B": (46, 34, 30, 255),    # boots/belt
}

GOD_TOP = """
..KK....KKKK....KK....
.KAAK..KAAAAK..KAAK...
.KAAAK.KAAAAK.KAAAK...
..KAAAKKYYYYKKAAAK....
...KAAKYYYYYYKAAK.....
....KRRRRRRRRRRK......
...KRRERRRRRRERRK.....
...KRRRRRRRRRRRRK.....
...KRrRRLLLLRRrRK.....
...KTRRRRRRRRRRTK.....
...KRTRRRRRRRRTRK.....
....KTTRRRRRRTTK......
..KKKKRRRRRRRRKKKK....
.KAAAKKRRRRRRKKAAAK...
KAAaAAKRRLLRRKAAaAAK..
KAAaAAKRLRRLRKAAaAAK..
KKAAAKKRRRRRRKKAAAKK..
.KRRK.KRRLLRRK.KRRK...
.KRrK.KRRRRRRK.KRrK...
.KRRK.KRLRRLRK.KRRK...
.KKKK.KRRRRRRK.KKKK...
.KRRK.KBBBBBBK.KRRK...
..KK..KBYYYYBK..KK....
......KRRRRRRK........
""".strip("\n")

GOD_LEGS_STAND = """
.....KRRKKKRRK........
.....KRRK.KRRK........
.....KBBK.KBBK........
.....KKK...KKK........
""".strip("\n")

GOD_LEGS_A = """
.....KRRK.KRRK........
....KBBK...KBBK.......
....KKK.....KKK.......
......................
""".strip("\n")


def orcgod(name, legs, bob):
    save_grid(name, ("." * 22 + "\n") * bob + GOD_TOP + "\n" + legs, GOD_PAL)


orcgod("orc_god_idle_f0", GOD_LEGS_STAND, 1)
orcgod("orc_god_idle_f1", GOD_LEGS_STAND, 0)
orcgod("orc_god_idle_f2", GOD_LEGS_STAND, 0)
orcgod("orc_god_idle_f3", GOD_LEGS_STAND, 1)
orcgod("orc_god_run_f0", GOD_LEGS_A, 1)
orcgod("orc_god_run_f1", GOD_LEGS_STAND, 0)
orcgod("orc_god_run_f2", GOD_LEGS_A, 1)
orcgod("orc_god_run_f3", GOD_LEGS_STAND, 0)

# ------------------------------------------------------ orc butcher boss ---
# wave-5 boss: fat orc in a blood-stained apron, cleaver in fist.
BUT_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "G": (110, 152, 62, 255),  # skin
    "g": (74, 106, 46, 255),   # skin shade
    "W": (226, 220, 206, 255), # apron
    "w": (196, 188, 172, 255), # apron shade
    "R": (162, 40, 44, 255),   # blood stains
    "A": (188, 196, 210, 255), # cleaver steel
    "a": (120, 128, 146, 255), # cleaver shade
    "D": (52, 40, 34, 255),    # strap / boots
    "T": (240, 236, 220, 255), # tusks
}

BUT_TOP = """
......KKKKKK......
.....KGGGGGGK.....
....KGGGGGGGGK....
....KGgRGGRgGK....
....KGGGGGGGGK....
....KGTGGGGTGK....
.....KTGGGGTK.....
....KGKKKKKKGK....
...KGGKWWWWKGGK...
..KGGKWWWWWWKGGK..
..KGKWWRWWWWKKGK..
.KGGKWWWRWWWWKGGK.
.KGKWWWWWWRWWKKGK.
.KGKWRWWWWWWWKAAK.
.KGKWWWWRWWWWKAaK.
..KKWWWWWWWRWKAaK.
...KWWRWWWWWWKAAK.
...KwWWWWWRWwK.K..
...KwWWWWWWWwK....
....KDWWWWWDK.....
""".strip("\n")

BUT_LEGS_STAND = """
....KGGKKGGK......
....KDDK.KDDK.....
.....KK...KK......
""".strip("\n")

BUT_LEGS_A = """
....KGGK.KGGK.....
...KDDK...KDDK....
....KK.....KK.....
""".strip("\n")

BUT_LEGS_B = """
....KGGKKGGK......
...KDDK..KDDK.....
....KK....KK......
""".strip("\n")


def butcher(name, legs, bob):
    save_grid(name, ("." * 18 + "\n") * bob + BUT_TOP + "\n" + legs, BUT_PAL)


butcher("orc_butcher_idle_f0", BUT_LEGS_STAND, 1)
butcher("orc_butcher_idle_f1", BUT_LEGS_STAND, 0)
butcher("orc_butcher_idle_f2", BUT_LEGS_STAND, 0)
butcher("orc_butcher_idle_f3", BUT_LEGS_STAND, 1)
butcher("orc_butcher_run_f0", BUT_LEGS_A, 1)
butcher("orc_butcher_run_f1", BUT_LEGS_STAND, 0)
butcher("orc_butcher_run_f2", BUT_LEGS_B, 1)
butcher("orc_butcher_run_f3", BUT_LEGS_STAND, 0)

# --------------------------------------------------- orc shaman king boss --
# wave-15 boss: robed orc mystic, skull mask, antler crown, orb staff.
SHK_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "P": (96, 60, 130, 255),   # robe purple
    "p": (66, 40, 94, 255),    # robe shade
    "W": (238, 234, 222, 255), # skull mask
    "w": (196, 190, 176, 255), # skull shade
    "G": (110, 152, 62, 255),  # orc hands
    "E": (60, 220, 90, 255),   # glowing eyes / orb
    "e": (26, 130, 60, 255),   # orb shade
    "Y": (226, 180, 62, 255),  # antler crown gold
    "S": (94, 66, 44, 255),    # staff wood
}

SHK_TOP = """
..KY.K......K.YK..
..KYYK......KYYK..
...KYYK....KYYK...
....KYKKKKKKYK....
....KPPPPPPPPK....
...KPWWWWWWWWPK...
...KPWEWWWWEWPK...
...KPWWWWWWWWPK...
...KPWwKWWKwWPK...
....KPWwWWwWPKKE..
....KPPKWWKPPKEeK.
...KPPPPPPPPPKKE..
..KPPPPPPPPPPKSK..
..KGKPPPPPPPPKSK..
..KGKpPPPPPPpKSK..
..KKKpPPPPPPpKSK..
....KpPPPPPPpKSK..
....KPPPPPPPPKSK..
...KPPPPPPPPPPKK..
""".strip("\n")

SHK_LEGS_STAND = """
...KpPPPPPPPPpK...
....KKKKKKKKKK....
""".strip("\n")

SHK_LEGS_A = """
...KpPPPPPPPPpK...
....KKKKKKKKKK....
""".strip("\n")


def shamanking(name, legs, bob):
    save_grid(name, ("." * 18 + "\n") * bob + SHK_TOP + "\n" + legs, SHK_PAL)


shamanking("orc_shamanking_idle_f0", SHK_LEGS_STAND, 1)
shamanking("orc_shamanking_idle_f1", SHK_LEGS_STAND, 0)
shamanking("orc_shamanking_idle_f2", SHK_LEGS_STAND, 0)
shamanking("orc_shamanking_idle_f3", SHK_LEGS_STAND, 1)
shamanking("orc_shamanking_run_f0", SHK_LEGS_A, 1)
shamanking("orc_shamanking_run_f1", SHK_LEGS_STAND, 0)
shamanking("orc_shamanking_run_f2", SHK_LEGS_A, 1)
shamanking("orc_shamanking_run_f3", SHK_LEGS_STAND, 0)

# ------------------------------------------------- berserker recolor -------
# orc_warrior with skin shifted to red + warpaint: an elite variant.


def recolor_to_red(src, dst):
    img = Image.open(src).convert("RGBA")
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            if a and g > r * 1.15 and g > b * 1.15 and g > 70:  # skin pixel
                h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
                h, l, s = 0.99, min(1.0, l * 1.2), min(1.0, s * 1.1)
                r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)
                px[x, y] = (int(r2 * 255), int(g2 * 255), int(b2 * 255), a)
    img.save(dst)


for anim in ("idle", "run"):
    for f in range(4):
        recolor_to_red(
            os.path.join(SPRITES, f"orc_warrior_{anim}_anim_f{f}.png"),
            os.path.join(OUT, f"orc_berserker_{anim}_f{f}.png"),
        )

# ------------------------------------------------------------- weapons -----
WHIP_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "H": (94, 62, 40, 255),    # leather handle
    "h": (128, 90, 56, 255),   # handle light
    "L": (168, 128, 84, 255),  # lash
    "l": (204, 168, 116, 255), # lash light
    "Y": (226, 180, 62, 255),  # gold pommel
}
save_grid("weapon_whip", """
......KKK.......
.....KLlLK......
....KL.KLK......
....KLK.KLK.....
....KLK.KLK.....
....KLLKLK......
.....KLLK.......
......KLK.......
......KhK.......
......KHK.......
......KHK.......
......KYK.......
.......K........
""", WHIP_PAL)

SCYTHE_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "B": (196, 208, 224, 255), # blade
    "b": (124, 138, 160, 255), # blade shade
    "S": (66, 48, 40, 255),    # shaft
    "s": (94, 70, 52, 255),    # shaft light
    "R": (140, 30, 40, 255),   # blood-red wrap
}
save_grid("weapon_scythe", """
..KKKKKK........
.KBBBBBBKK......
.KbbBBBBBBK.....
....KKKbBBK.....
......KsKBK.....
......KSK.K.....
......KsK.......
......KSK.......
......KRK.......
......KSK.......
......KsK.......
......KSK.......
......KsK.......
.......K........
""", SCYTHE_PAL)

# ------------------------------------------------------------- the nun -----
# proper nun: black habit, white coif around the face, gold cross.
NUN_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "B": (40, 36, 48, 255),    # habit black
    "b": (58, 53, 68, 255),    # habit highlight
    "W": (238, 236, 228, 255), # coif white
    "F": (228, 186, 152, 255), # skin
    "f": (198, 152, 120, 255), # skin shade
    "Y": (226, 180, 62, 255),  # gold cross
}

NUN_TOP = """
.....KKKK.....
....KBBBBK....
...KBBBBBBK...
...KBWWWWBK...
...KBWFFWBK...
...KBWFFWBK...
...KBWfFWBK...
....KWFFWK....
....KBWWBK....
...KBBBBBBK...
..KBBBWWBBBK..
..KBBBWYWBBK..
..KBbBBYBBbK..
..KBbBBBBBbK..
...KBBBBBBK...
...KBBBBBBK...
""".strip("\n")

NUN_LEGS_STAND = """
...KBBBBBBK...
....KbKKbK....
....KK..KK....
""".strip("\n")

NUN_LEGS_A = """
...KBBBBBBK...
...KbK..KbK...
...KK....KK...
""".strip("\n")

NUN_LEGS_B = """
...KBBBBBBK...
....KbKKbK....
...KK....KK...
""".strip("\n")


def nun(name, legs, bob):
    save_grid(name, ("." * 14 + "\n") * bob + NUN_TOP + "\n" + legs, NUN_PAL)


nun("nun_idle_f0", NUN_LEGS_STAND, 1)
nun("nun_idle_f1", NUN_LEGS_STAND, 0)
nun("nun_idle_f2", NUN_LEGS_STAND, 0)
nun("nun_idle_f3", NUN_LEGS_STAND, 1)
nun("nun_run_f0", NUN_LEGS_A, 1)
nun("nun_run_f1", NUN_LEGS_STAND, 0)
nun("nun_run_f2", NUN_LEGS_B, 1)
nun("nun_run_f3", NUN_LEGS_STAND, 0)

# --------------------------------------------------------- quasimodo -------
# hunched bell-ringer: hump on the back, head pushed forward, ragged tunic.
QUA_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "D": (58, 44, 34, 255),    # messy hair
    "F": (224, 178, 140, 255), # skin
    "f": (192, 142, 106, 255), # skin shade
    "T": (134, 96, 58, 255),   # tunic
    "t": (100, 70, 44, 255),   # tunic shade
    "R": (146, 42, 40, 255),   # patched sleeve
    "b": (62, 48, 38, 255),    # boots
}

QUA_TOP = """
....KKK.........
..KKTTTKK.......
.KTTTTTTTK......
.KTTTTTTTTKKK...
.KtTTTTTKDDDDK..
.KtTTTTKDDDDDDK.
.KtTTTTKDFFFFDK.
..KTTTTKFFfFFK..
..KTTTTKFFFFK...
..KTTTTTKFFK....
..KRTTTTTTTK....
..KRtTTTTTTK....
...KtTTTTTK.....
""".strip("\n")

QUA_LEGS_STAND = """
...KTTKKTTK.....
....KbK.KbK.....
....KK..KK......
""".strip("\n")

QUA_LEGS_A = """
...KTTK.KTTK....
...KbK...KbK....
...KK.....KK....
""".strip("\n")

QUA_LEGS_B = """
...KTTKKTTK.....
...KbK...KbK....
....KK...KK.....
""".strip("\n")


def quasi(name, legs, bob):
    save_grid(name, ("." * 16 + "\n") * bob + QUA_TOP + "\n" + legs, QUA_PAL)


quasi("quasi_idle_f0", QUA_LEGS_STAND, 1)
quasi("quasi_idle_f1", QUA_LEGS_STAND, 0)
quasi("quasi_idle_f2", QUA_LEGS_STAND, 0)
quasi("quasi_idle_f3", QUA_LEGS_STAND, 1)
quasi("quasi_run_f0", QUA_LEGS_A, 1)
quasi("quasi_run_f1", QUA_LEGS_STAND, 0)
quasi("quasi_run_f2", QUA_LEGS_B, 1)
quasi("quasi_run_f3", QUA_LEGS_STAND, 0)

# ---------------------------------------------------------- orc grunt ------
# the basic orc, redrawn by hand: broad jaw, tusks, red eyes, loincloth,
# wooden club — replaces the downscaled CraftPix grunt as the wave-1 orc.
GRU_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "G": (116, 158, 66, 255),  # skin
    "g": (80, 112, 48, 255),   # skin shade
    "E": (232, 58, 48, 255),   # eyes
    "T": (240, 236, 220, 255), # tusks
    "B": (110, 76, 46, 255),   # loincloth
    "b": (74, 52, 34, 255),    # loincloth shade
    "W": (140, 100, 58, 255),  # club wood
    "w": (100, 70, 42, 255),   # club shade
}

GRU_TOP = """
....KKKKK......
...KGGGGGK.....
..KGGGGGGGK....
..KGEGGGEGK....
..KGGGGGGGK.K..
..KGgGGGgGKKWK.
..KTGGGGGTKWwK.
..KGTGGGTGKWwK.
...KGGGGGKKWwK.
..KGGGGGGGKWK..
.KGgKGGGKgKWK..
.KGK.KGGGKKK...
.KK..KGGGGK....
....KBBBBBK....
....KbBBBbK....
""".strip("\n")

GRU_LEGS_STAND = """
....KGGKGGK....
....KgK.KgK....
.....K...K.....
""".strip("\n")

GRU_LEGS_A = """
....KGGK.KGGK..
...KgK....KgK..
....K......K...
""".strip("\n")

GRU_LEGS_B = """
..KGGK.KGGK....
..KgK....KgK...
...K......K....
""".strip("\n")


def grunt(name, legs, bob):
    save_grid(name, ("." * 15 + "\n") * bob + GRU_TOP + "\n" + legs, GRU_PAL)


grunt("orc_grunt_idle_f0", GRU_LEGS_STAND, 1)
grunt("orc_grunt_idle_f1", GRU_LEGS_STAND, 0)
grunt("orc_grunt_idle_f2", GRU_LEGS_STAND, 0)
grunt("orc_grunt_idle_f3", GRU_LEGS_STAND, 1)
grunt("orc_grunt_run_f0", GRU_LEGS_A, 1)
grunt("orc_grunt_run_f1", GRU_LEGS_STAND, 0)
grunt("orc_grunt_run_f2", GRU_LEGS_B, 1)
grunt("orc_grunt_run_f3", GRU_LEGS_STAND, 0)

# ------------------------------------------------------------- monk --------
# dev-only test hero: bald, saffron robe, gold sash, serene.
MON_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "F": (228, 186, 152, 255), # skin
    "f": (198, 152, 120, 255), # skin shade
    "R": (208, 122, 40, 255),  # robe
    "r": (168, 92, 30, 255),   # robe shade
    "Y": (226, 180, 62, 255),  # sash
    "b": (74, 52, 34, 255),    # sandals
}

MON_TOP = """
.....KKKK.....
....KFFFFK....
...KFFFFFFK...
...KFKFFKFK...
...KFFFFFFK...
....KFffFK....
....KRRRRK....
...KRRRRRRK...
..KRRRRRRRRK..
..KFKRRRRKFK..
..KFKRRRRKFK..
..KKKRYYRKKK..
...KRRYYRRK...
...KRRRRRRK...
...KrRRRRrK...
...KrRRRRrK...
""".strip("\n")

MON_LEGS_STAND = """
...KRRRRRRK...
....KbKKbK....
.....K..K.....
""".strip("\n")

MON_LEGS_A = """
...KRRRRRRK...
...KbK..KbK...
....K....K....
""".strip("\n")

MON_LEGS_B = """
...KRRRRRRK...
....KbKKbK....
...K......K...
""".strip("\n")


def monk(name, legs, bob):
    save_grid(name, ("." * 14 + "\n") * bob + MON_TOP + "\n" + legs, MON_PAL)


monk("monk_idle_f0", MON_LEGS_STAND, 1)
monk("monk_idle_f1", MON_LEGS_STAND, 0)
monk("monk_idle_f2", MON_LEGS_STAND, 0)
monk("monk_idle_f3", MON_LEGS_STAND, 1)
monk("monk_run_f0", MON_LEGS_A, 1)
monk("monk_run_f1", MON_LEGS_STAND, 0)
monk("monk_run_f2", MON_LEGS_B, 1)
monk("monk_run_f3", MON_LEGS_STAND, 0)

# ---------------------------------------------------------- assassin -------
# hooded killer: slate hood and mask, only the eyes show, red sash.
ASN_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "H": (56, 62, 80, 255),    # hood
    "h": (78, 86, 108, 255),   # hood light
    "M": (40, 44, 58, 255),    # mask / dark cloth
    "E": (214, 230, 255, 255), # eye slits
    "R": (146, 42, 40, 255),   # sash
    "b": (34, 38, 50, 255),    # boots
}

ASN_TOP = """
.....KKKK.....
....KHHHHK....
...KHHHHHHK...
...KHhhhhHK...
...KHEhhEHK...
...KHMMMMHK...
....KMMMMK....
....KHHHHK....
...KHHHHHHK...
..KHHHHHHHHK..
..KhHHHHHHhK..
..KhHRRRRHhK..
..KKHHHHHHKK..
...KMHHHHMK...
...KMMMMMMK...
""".strip("\n")

ASN_LEGS_STAND = """
...KMMKKMMK...
....KbK.KbK...
....KK...KK...
""".strip("\n")

ASN_LEGS_A = """
...KMMK.KMMK..
...KbK...KbK..
...KK.....KK..
""".strip("\n")

ASN_LEGS_B = """
..KMMK.KMMK...
..KbK...KbK...
...KK...KK....
""".strip("\n")


def assassin(name, legs, bob):
    save_grid(name, ("." * 14 + "\n") * bob + ASN_TOP + "\n" + legs, ASN_PAL)


assassin("assassin_idle_f0", ASN_LEGS_STAND, 1)
assassin("assassin_idle_f1", ASN_LEGS_STAND, 0)
assassin("assassin_idle_f2", ASN_LEGS_STAND, 0)
assassin("assassin_idle_f3", ASN_LEGS_STAND, 1)
assassin("assassin_run_f0", ASN_LEGS_A, 1)
assassin("assassin_run_f1", ASN_LEGS_STAND, 0)
assassin("assassin_run_f2", ASN_LEGS_B, 1)
assassin("assassin_run_f3", ASN_LEGS_STAND, 0)

BDG_PAL = {
    "K": (24, 18, 26, 255),
    "B": (196, 208, 224, 255),  # blade
    "b": (126, 134, 152, 255),  # blade shade
    "H": (74, 52, 34, 255),     # grip
    "P": (180, 140, 255, 255),  # arcane gem
    "p": (110, 70, 190, 255),   # gem shade
}
save_grid("weapon_blast_dagger", """
....K....
...KBK...
...KBbK..
...KBbK..
...KBbK..
..KKBKK..
...KHK...
...KPK...
...KpK...
....K....
""", BDG_PAL)

SHUR_PAL = {
    "K": (24, 18, 26, 255),
    "A": (196, 204, 218, 255),
    "a": (126, 134, 152, 255),
}
save_grid("weapon_shuriken", """
....K....
...KAK...
.K.KaK.K.
KAKaKaKAK
.KaK.KaK.
KAKaKaKAK
.K.KaK.K.
...KAK...
....K....
""", SHUR_PAL)

# ---------------------------------------------------------- molotov --------
MOL_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "R": (238, 130, 32, 255),  # rag flame
    "r": (252, 210, 96, 255),  # flame core
    "W": (222, 214, 196, 255), # rag cloth
    "G": (94, 138, 110, 200),  # green glass
    "g": (66, 104, 82, 220),   # glass shade
    "Y": (206, 142, 38, 255),  # amber liquid
}
save_grid("weapon_molotov", """
...Rr...
...RR...
..KWRK..
..KWK...
..KGgK..
..KGgK..
.KGGGgK.
.KGYYgK.
.KGYYgK.
.KGYYgK.
..KKKK..
""", MOL_PAL)

# ------------------------------------------------------------ cave tiles ---
# procedural rock floor/wall tiles, deterministic per variant.
def cave_floor(i):
    random.seed(4200 + i)
    img = Image.new("RGBA", (16, 16))
    px = img.load()
    for y in range(16):
        for x in range(16):
            v = random.random()
            if v < 0.72: c = (68, 59, 55)
            elif v < 0.92: c = (61, 53, 50)
            else: c = (77, 66, 60)
            px[x, y] = (*c, 255)
    for _ in range(2):  # cracks
        cx, cy = random.randint(1, 14), random.randint(1, 14)
        for _ in range(random.randint(3, 6)):
            px[cx, cy] = (38, 32, 32, 255)
            cx = max(0, min(15, cx + random.randint(-1, 1)))
            cy = max(0, min(15, cy + random.randint(-1, 1)))
    for _ in range(random.randint(2, 4)):  # pebbles
        px[random.randint(0, 15), random.randint(0, 15)] = (90, 78, 68, 255)
    img.save(os.path.join(OUT, f"cave_floor_{i}.png"))


def cave_wall(i):
    random.seed(6200 + i)
    img = Image.new("RGBA", (16, 16))
    px = img.load()
    for y in range(16):
        for x in range(16):
            v = random.random()
            if v < 0.75: c = (27, 22, 31)
            elif v < 0.93: c = (23, 19, 27)
            else: c = (36, 30, 42)
            px[x, y] = (*c, 255)
    for _ in range(random.randint(2, 3)):  # jagged highlight veins
        cx, cy = random.randint(1, 14), random.randint(1, 14)
        for _ in range(random.randint(2, 5)):
            px[cx, cy] = (46, 39, 54, 255)
            cx = max(0, min(15, cx + random.randint(-1, 1)))
            cy = max(0, min(15, cy + random.randint(-1, 1)))
    img.save(os.path.join(OUT, f"cave_wall_{i}.png"))


for i in range(4):
    cave_floor(i)
for i in range(2):
    cave_wall(i)

STAL_PAL = {
    "K": (24, 18, 26, 255),
    "S": (74, 64, 72, 255),
    "s": (52, 44, 52, 255),
    "W": (96, 86, 94, 255),
}
save_grid("stalagmite_big", """
.....KK.....
....KWSK....
....KSsK....
...KWSSsK...
...KSSssK...
..KWSSSssK..
..KSSssssK..
.KSSSSsssKK.
.KWSSsssssK.
KSSSSSsssssK
KKKKKKKKKKKK
""", STAL_PAL)
save_grid("stalagmite_small", """
...KK...
..KWSK..
..KSsK..
.KSSssK.
.KWSssK.
KSSSsssK
KKKKKKKK
""", STAL_PAL)

MUSH_PAL = {
    "K": (20, 24, 30, 255),
    "C": (72, 210, 208, 255),   # glowing cap
    "c": (38, 130, 140, 255),
    "W": (200, 255, 250, 255),  # glow core
    "S": (90, 96, 104, 255),    # stem
}
save_grid("mushroom_glow_f0", """
..KKKK..
.KCCCCK.
KCWCCcCK
KCCCCccK
.KKSKK..
...KSK..
...KK...
""", MUSH_PAL)
save_grid("mushroom_glow_f1", """
..KKKK..
.KCWCCK.
KCCCCcCK
KCWCCccK
.KKSKK..
...KSK..
...KK...
""", MUSH_PAL)

TORCH_PAL = {
    "K": (24, 18, 26, 255),
    "W": (110, 76, 46, 255),   # wood
    "w": (74, 52, 34, 255),
    "R": (238, 130, 32, 255),  # flame
    "Y": (252, 210, 96, 255),
    "C": (255, 246, 200, 255), # core
    "S": (90, 86, 96, 255),    # iron bracket
}
save_grid("torch_f0", """
...RY...
..RYYR..
..RYCR..
...YY...
..KWWK..
.SKWwKS.
..KWwK..
..KWwK..
...KK...
""", TORCH_PAL)
save_grid("torch_f1", """
..R.Y...
..RYYR..
.RYCCYR.
...YY...
..KWWK..
.SKWwKS.
..KWwK..
..KWwK..
...KK...
""", TORCH_PAL)

BONE_PAL = {
    "K": (30, 26, 32, 255),
    "W": (216, 208, 190, 255),
    "w": (170, 160, 142, 255),
}
save_grid("bone_pile", """
............
..KWK..KWWK.
.KWwWKKWwwK.
..KKWWWwKK..
....KKKK....
""", BONE_PAL)

# ----------------------------------------------------- the hanged king -----
# set piece on the east wall: the King of the Humans, hanged and bleeding.
KING_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "C": (126, 124, 136, 255), # chain
    "G": (226, 180, 62, 255),  # crown
    "F": (216, 190, 164, 255), # skin (pale)
    "f": (184, 156, 130, 255), # skin shade
    "H": (150, 138, 120, 255), # grey beard/hair
    "P": (104, 48, 116, 255),  # royal robe
    "p": (76, 34, 86, 255),    # robe shade
    "R": (168, 28, 34, 255),   # blood
    "r": (210, 48, 52, 255),   # fresh blood
    "B": (52, 40, 34, 255),    # boots
}

KING_F0 = """
........KCK.......
........KCK.......
........KCK.......
.......KCCCK......
......KG.G.GK.....
......KGGGGGK.....
......KFFFFfK.....
......KFfFfFK.....
......KHFFFHK.....
.......KHHHK......
.....KPPPPPPPK....
....KPPGGGGPPPK...
....KPPPPPPPPPK...
...KPKPPRPPPKPK...
...KPKPPPPRPKPK...
...KPKpPPPPpKPK...
...KFKpPRPPpKFK...
...KKKpPPPPpKKK...
.....KpPPPPpK.....
.....KPPPPPPK.....
......KPKKPK......
......KPK.KPK.....
......KBK.KBK.....
......KKK.KKK.....
.......r...r......
..................
.......r..........
..........r.......
""".strip("\n")

KING_F1 = """
........KCK.......
........KCK.......
........KCK.......
.......KCCCK......
......KG.G.GK.....
......KGGGGGK.....
......KFFFFfK.....
......KFfFfFK.....
......KHFFFHK.....
.......KHHHK......
.....KPPPPPPPK....
....KPPGGGGPPPK...
....KPPPPPPPPPK...
...KPKPPRPPPKPK...
...KPKPPPPRPKPK...
...KPKpPPPPpKPK...
...KFKpPRPPpKFK...
...KKKpPPPPpKKK...
.....KpPPPPpK.....
.....KPPPPPPK.....
......KPKKPK......
......KPK.KPK.....
......KBK.KBK.....
......KKK.KKK.....
..................
.......r...r......
..........r.......
.......r..........
""".strip("\n")

save_grid("hanging_king_f0", KING_F0, KING_PAL)
save_grid("hanging_king_f1", KING_F1, KING_PAL)

# ---------------------------------------------------------- ui key icon ----
KEY_PAL = {
    "K": (24, 18, 26, 255),
    "Y": (226, 180, 62, 255),
    "y": (168, 128, 44, 255),
}
save_grid("ui_key", """
.KKKK.......
KYYYYK......
KY..YKKKKKKK
KY..YYYYYYYK
KYYYYKKYKYKK
.KKKK..KyKy.
........K.K.
""", KEY_PAL)

# ---------------------------------------------------------- upgrade card ---
# 44x60 parchment card with gold pixel corners, used by the level-up UI.
card = Image.new("RGBA", (44, 60), (0, 0, 0, 0))
px = card.load()
EDGE = (24, 18, 26, 255)
GOLD = (226, 180, 62, 255)
PAPER = (222, 202, 158, 255)
PAPER2 = (206, 184, 138, 255)
for y in range(60):
    for x in range(44):
        if x in (0, 43) or y in (0, 59):
            px[x, y] = EDGE
        elif x in (1, 42) or y in (1, 58):
            px[x, y] = GOLD
        else:
            px[x, y] = PAPER2 if (x + y) % 7 == 0 else PAPER
for cx, cy in ((3, 3), (38, 3), (3, 54), (38, 54)):
    for dx in range(3):
        for dy in range(3):
            if dx + dy < 3:
                px[cx + dx, cy + dy] = GOLD
card.save(os.path.join(OUT, "card.png"))

print("custom art written:", sorted(os.listdir(OUT)))
