#!/usr/bin/env python3
"""Generate the original pixel-art sprites for Orc Slasher (campfire, gems,
effects, the Orc Warchief boss and berserker recolors). Output: assets/custom/.

All art here is hand-authored in-code (CC0, do whatever you want with it)."""
import colorsys
import os
from PIL import Image

OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "custom")
SPRITES = os.path.join(os.path.dirname(__file__), "..", "assets", "sprites")
os.makedirs(OUT, exist_ok=True)


def save_grid(name, grid, palette):
    rows = [r for r in grid.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    img = Image.new("RGBA", (w, len(rows)), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch in palette:
                px[x, y] = palette[ch]
    img.save(os.path.join(OUT, name + ".png"))
    return img


# ---------------------------------------------------------------- campfire --
FIRE_PAL = {
    "K": (34, 24, 26, 255),    # log outline
    "L": (92, 62, 40, 255),    # log
    "l": (128, 90, 56, 255),   # log light
    "S": (60, 56, 64, 255),    # stone
    "s": (90, 86, 96, 255),    # stone light
    "R": (206, 66, 28, 255),   # flame red
    "O": (238, 130, 32, 255),  # flame orange
    "Y": (252, 210, 96, 255),  # flame yellow
    "W": (255, 246, 200, 255), # flame core
}

CAMPFIRE = [
"""
................
................
................
......R.R.......
.....RORRO......
....ROYYOOR.....
....ROYWYOR.....
.....OYWWYO.....
.....ROYYOR.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
......R..R......
.....R.RR.......
.....RROORR.....
....ROYOYOR.....
.....OYWYYO.....
....ROYWWYOR....
.....OYYYYO.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
................
.......RR.......
......ROOR......
.....ROYYOR.....
....ROYWWYOR....
....ROYWWYOR....
.....OYWYYO.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
.....R..........
......RR..R.....
.....RORRRO.....
.....ROYYOR.....
....ROYWYOOR....
.....OYWWYO.....
.....ROYYOR.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
]
for i, g in enumerate(CAMPFIRE):
    save_grid(f"campfire_f{i}", g, FIRE_PAL)

# ---------------------------------------------------------------- xp gem ----
GEM_PAL = {
    "K": (20, 40, 24, 255),
    "G": (52, 168, 83, 255),
    "g": (30, 110, 54, 255),
    "W": (198, 255, 208, 255),
}
save_grid("xp_gem_f0", """
...KK...
..KGGK..
.KGWGGK.
.KGGGgK.
.KGGggK.
..KggK..
...KK...
""", GEM_PAL)
save_grid("xp_gem_f1", """
...KK...
..KWGK..
.KGGGGK.
.KGGGgK.
.KWGggK.
..KggK..
...KK...
""", GEM_PAL)

# ------------------------------------------------------------ shaman bolt ---
BOLT_PAL = {
    "G": (86, 224, 90, 255),
    "g": (34, 140, 60, 190),
    "W": (222, 255, 200, 255),
}
save_grid("shaman_bolt_f0", """
..gg..
.gGGg.
gGWWGg
gGWWGg
.gGGg.
..gg..
""", BOLT_PAL)
save_grid("shaman_bolt_f1", """
..gg..
.gGGg.
gGGWGg
gGWGGg
.gGGg.
..gg..
""", BOLT_PAL)

# ------------------------------------------------------------ slash arc -----
SLASH_PAL = {
    "W": (255, 255, 255, 235),
    "S": (188, 210, 232, 200),
    "s": (130, 158, 190, 120),
}
save_grid("slash_f0", """
................
............ss..
..........sSSs..
........sSSWs...
......sSWWs.....
....sSWWs.......
...sSWs.........
...sWs..........
...ss...........
................
""", SLASH_PAL)
save_grid("slash_f1", """
................
...........ss...
.........sSWWs..
.......sSWWWs...
.....sSWWWs.....
...sSWWWs.......
..sSWWs.........
..sWWs..........
..sss...........
................
""", SLASH_PAL)
save_grid("slash_f2", """
................
..........s.....
........sSs.....
......sSSs......
....sSSs........
...sSs..........
..ss............
..s.............
................
................
""", SLASH_PAL)

# ------------------------------------------------------- orc warchief boss --
# Original 18x26 hulking orc: iron pauldrons, gold-trimmed helm horns,
# red warpaint, glowing eyes, big tusks.
WCH_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "G": (110, 152, 62, 255),  # skin
    "g": (74, 106, 46, 255),   # skin shade
    "D": (46, 36, 34, 255),    # hair / dark leather
    "W": (240, 236, 220, 255), # tusk / teeth
    "R": (255, 64, 48, 255),   # glowing eyes
    "P": (182, 40, 46, 255),   # warpaint / banner cloth
    "A": (118, 116, 130, 255), # iron
    "a": (74, 72, 88, 255),    # iron shade
    "Y": (226, 180, 62, 255),  # gold trim
    "B": (82, 58, 44, 255),    # pants
    "b": (52, 40, 34, 255),    # boots
}

WCH_TOP = """
....KK......KK....
...KYYK....KYYK...
...KYAYK..KYAYK...
....KAAK..KAAK....
....KAAAKKAAAK....
.....KAAAAAAK.....
.....KAaaaaAK.....
....KGGGGGGGGK....
....KGPGGGGPGK....
...KGGRGGGGRGGK...
...KGGGGggGGGGK...
...KGWGgggGGWGK...
....KWGGGGGGWK....
.....KGWWWWGK.....
..KAAKKGGGGKKAAK..
.KAaaAKKKKKKAaaAK.
.KAaaAKPGGPKAaaAK.
.KKAAKKGGGGKKAAKK.
..KgK.KgGGgK.KgK..
..KgK.KGGGGK.KgK..
""".strip("\n")

WCH_LEGS_STAND = """
......KBBBBK......
......KB..BK......
......KbK.KbK.....
.....KbbK.KbbK....
......KK...KK.....
""".strip("\n")

WCH_LEGS_A = """
......KBBBBK......
.....KBK..KBK.....
....KbbK...KbK....
....KbbK..KbbK....
.....KK....KK.....
""".strip("\n")

WCH_LEGS_B = """
......KBBBBK......
.....KBK..KBK.....
....KbK...KbbK....
....KbbK..KbbK....
.....KK....KK.....
""".strip("\n")


def warchief(name, legs, bob):
    body = ("." * 18 + "\n") * bob + WCH_TOP + "\n" + legs
    save_grid(name, body, WCH_PAL)


warchief("orc_warchief_idle_f0", WCH_LEGS_STAND, 1)
warchief("orc_warchief_idle_f1", WCH_LEGS_STAND, 0)
warchief("orc_warchief_idle_f2", WCH_LEGS_STAND, 0)
warchief("orc_warchief_idle_f3", WCH_LEGS_STAND, 1)
warchief("orc_warchief_run_f0", WCH_LEGS_A, 1)
warchief("orc_warchief_run_f1", WCH_LEGS_STAND, 0)
warchief("orc_warchief_run_f2", WCH_LEGS_B, 1)
warchief("orc_warchief_run_f3", WCH_LEGS_STAND, 0)

# ------------------------------------------------- berserker recolor -------
# orc_warrior with skin shifted to red + warpaint: an elite variant.


def recolor_to_red(src, dst):
    img = Image.open(src).convert("RGBA")
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            if a and g > r * 1.15 and g > b * 1.15 and g > 70:  # skin pixel
                h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
                h, l, s = 0.99, min(1.0, l * 1.2), min(1.0, s * 1.1)
                r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)
                px[x, y] = (int(r2 * 255), int(g2 * 255), int(b2 * 255), a)
    img.save(dst)


for anim in ("idle", "run"):
    for f in range(4):
        recolor_to_red(
            os.path.join(SPRITES, f"orc_warrior_{anim}_anim_f{f}.png"),
            os.path.join(OUT, f"orc_berserker_{anim}_f{f}.png"),
        )

# ---------------------------------------------------------- upgrade card ---
# 44x60 parchment card with gold pixel corners, used by the level-up UI.
card = Image.new("RGBA", (44, 60), (0, 0, 0, 0))
px = card.load()
EDGE = (24, 18, 26, 255)
GOLD = (226, 180, 62, 255)
PAPER = (222, 202, 158, 255)
PAPER2 = (206, 184, 138, 255)
for y in range(60):
    for x in range(44):
        if x in (0, 43) or y in (0, 59):
            px[x, y] = EDGE
        elif x in (1, 42) or y in (1, 58):
            px[x, y] = GOLD
        else:
            px[x, y] = PAPER2 if (x + y) % 7 == 0 else PAPER
for cx, cy in ((3, 3), (38, 3), (3, 54), (38, 54)):
    for dx in range(3):
        for dy in range(3):
            if dx + dy < 3:
                px[cx + dx, cy + dy] = GOLD
card.save(os.path.join(OUT, "card.png"))

print("custom art written:", sorted(os.listdir(OUT)))
