#!/usr/bin/env python3
"""Generate the original pixel-art sprites for Orc Slasher (campfire, gems,
effects, the Orc Warchief boss and berserker recolors). Output: assets/custom/.

All art here is hand-authored in-code (CC0, do whatever you want with it)."""
import colorsys
import os
from PIL import Image

OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "custom")
SPRITES = os.path.join(os.path.dirname(__file__), "..", "assets", "sprites")
os.makedirs(OUT, exist_ok=True)


def save_grid(name, grid, palette):
    rows = [r for r in grid.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    img = Image.new("RGBA", (w, len(rows)), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch in palette:
                px[x, y] = palette[ch]
    img.save(os.path.join(OUT, name + ".png"))
    return img


# ---------------------------------------------------------------- campfire --
FIRE_PAL = {
    "K": (34, 24, 26, 255),    # log outline
    "L": (92, 62, 40, 255),    # log
    "l": (128, 90, 56, 255),   # log light
    "S": (60, 56, 64, 255),    # stone
    "s": (90, 86, 96, 255),    # stone light
    "R": (206, 66, 28, 255),   # flame red
    "O": (238, 130, 32, 255),  # flame orange
    "Y": (252, 210, 96, 255),  # flame yellow
    "W": (255, 246, 200, 255), # flame core
}

CAMPFIRE = [
"""
................
................
................
......R.R.......
.....RORRO......
....ROYYOOR.....
....ROYWYOR.....
.....OYWWYO.....
.....ROYYOR.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
......R..R......
.....R.RR.......
.....RROORR.....
....ROYOYOR.....
.....OYWYYO.....
....ROYWWYOR....
.....OYYYYO.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
................
.......RR.......
......ROOR......
.....ROYYOR.....
....ROYWWYOR....
....ROYWWYOR....
.....OYWYYO.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
"""
................
................
.....R..........
......RR..R.....
.....RORRRO.....
.....ROYYOR.....
....ROYWYOOR....
.....OYWWYO.....
.....ROYYOR.....
......OYYO......
...K.KOYYOK.K...
..KLKLlLLlKLK...
..KLLlKKKKLLK...
...s.KLLLLK.s...
..s.s.KKKK.s.s..
................
""",
]
for i, g in enumerate(CAMPFIRE):
    save_grid(f"campfire_f{i}", g, FIRE_PAL)

# ---------------------------------------------------------------- xp gem ----
GEM_PAL = {
    "K": (20, 40, 24, 255),
    "G": (52, 168, 83, 255),
    "g": (30, 110, 54, 255),
    "W": (198, 255, 208, 255),
}
save_grid("xp_gem_f0", """
...KK...
..KGGK..
.KGWGGK.
.KGGGgK.
.KGGggK.
..KggK..
...KK...
""", GEM_PAL)
save_grid("xp_gem_f1", """
...KK...
..KWGK..
.KGGGGK.
.KGGGgK.
.KWGggK.
..KggK..
...KK...
""", GEM_PAL)

# ------------------------------------------------------------ shaman bolt ---
BOLT_PAL = {
    "G": (86, 224, 90, 255),
    "g": (34, 140, 60, 190),
    "W": (222, 255, 200, 255),
}
save_grid("shaman_bolt_f0", """
..gg..
.gGGg.
gGWWGg
gGWWGg
.gGGg.
..gg..
""", BOLT_PAL)
save_grid("shaman_bolt_f1", """
..gg..
.gGGg.
gGGWGg
gGWGGg
.gGGg.
..gg..
""", BOLT_PAL)

# ------------------------------------------------------------ slash arc -----
SLASH_PAL = {
    "W": (255, 255, 255, 235),
    "S": (188, 210, 232, 200),
    "s": (130, 158, 190, 120),
}
save_grid("slash_f0", """
................
............ss..
..........sSSs..
........sSSWs...
......sSWWs.....
....sSWWs.......
...sSWs.........
...sWs..........
...ss...........
................
""", SLASH_PAL)
save_grid("slash_f1", """
................
...........ss...
.........sSWWs..
.......sSWWWs...
.....sSWWWs.....
...sSWWWs.......
..sSWWs.........
..sWWs..........
..sss...........
................
""", SLASH_PAL)
save_grid("slash_f2", """
................
..........s.....
........sSs.....
......sSSs......
....sSSs........
...sSs..........
..ss............
..s.............
................
................
""", SLASH_PAL)

# ------------------------------------------------------- orc warchief boss --
# Original 18x26 hulking orc: iron pauldrons, gold-trimmed helm horns,
# red warpaint, glowing eyes, big tusks.
WCH_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "G": (110, 152, 62, 255),  # skin
    "g": (74, 106, 46, 255),   # skin shade
    "D": (46, 36, 34, 255),    # hair / dark leather
    "W": (240, 236, 220, 255), # tusk / teeth
    "R": (255, 64, 48, 255),   # glowing eyes
    "P": (182, 40, 46, 255),   # warpaint / banner cloth
    "A": (118, 116, 130, 255), # iron
    "a": (74, 72, 88, 255),    # iron shade
    "Y": (226, 180, 62, 255),  # gold trim
    "B": (82, 58, 44, 255),    # pants
    "b": (52, 40, 34, 255),    # boots
}

WCH_TOP = """
....KK......KK....
...KYYK....KYYK...
...KYAYK..KYAYK...
....KAAK..KAAK....
....KAAAKKAAAK....
.....KAAAAAAK.....
.....KAaaaaAK.....
....KGGGGGGGGK....
....KGPGGGGPGK....
...KGGRGGGGRGGK...
...KGGGGggGGGGK...
...KGWGgggGGWGK...
....KWGGGGGGWK....
.....KGWWWWGK.....
..KAAKKGGGGKKAAK..
.KAaaAKKKKKKAaaAK.
.KAaaAKPGGPKAaaAK.
.KKAAKKGGGGKKAAKK.
..KgK.KgGGgK.KgK..
..KgK.KGGGGK.KgK..
""".strip("\n")

WCH_LEGS_STAND = """
......KBBBBK......
......KB..BK......
......KbK.KbK.....
.....KbbK.KbbK....
......KK...KK.....
""".strip("\n")

WCH_LEGS_A = """
......KBBBBK......
.....KBK..KBK.....
....KbbK...KbK....
....KbbK..KbbK....
.....KK....KK.....
""".strip("\n")

WCH_LEGS_B = """
......KBBBBK......
.....KBK..KBK.....
....KbK...KbbK....
....KbbK..KbbK....
.....KK....KK.....
""".strip("\n")


def warchief(name, legs, bob):
    body = ("." * 18 + "\n") * bob + WCH_TOP + "\n" + legs
    save_grid(name, body, WCH_PAL)


warchief("orc_warchief_idle_f0", WCH_LEGS_STAND, 1)
warchief("orc_warchief_idle_f1", WCH_LEGS_STAND, 0)
warchief("orc_warchief_idle_f2", WCH_LEGS_STAND, 0)
warchief("orc_warchief_idle_f3", WCH_LEGS_STAND, 1)
warchief("orc_warchief_run_f0", WCH_LEGS_A, 1)
warchief("orc_warchief_run_f1", WCH_LEGS_STAND, 0)
warchief("orc_warchief_run_f2", WCH_LEGS_B, 1)
warchief("orc_warchief_run_f3", WCH_LEGS_STAND, 0)

# ------------------------------------------------------ orc butcher boss ---
# wave-5 boss: fat orc in a blood-stained apron, cleaver in fist.
BUT_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "G": (110, 152, 62, 255),  # skin
    "g": (74, 106, 46, 255),   # skin shade
    "W": (226, 220, 206, 255), # apron
    "w": (196, 188, 172, 255), # apron shade
    "R": (162, 40, 44, 255),   # blood stains
    "A": (188, 196, 210, 255), # cleaver steel
    "a": (120, 128, 146, 255), # cleaver shade
    "D": (52, 40, 34, 255),    # strap / boots
    "T": (240, 236, 220, 255), # tusks
}

BUT_TOP = """
......KKKKKK......
.....KGGGGGGK.....
....KGGGGGGGGK....
....KGgRGGRgGK....
....KGGGGGGGGK....
....KGTGGGGTGK....
.....KTGGGGTK.....
....KGKKKKKKGK....
...KGGKWWWWKGGK...
..KGGKWWWWWWKGGK..
..KGKWWRWWWWKKGK..
.KGGKWWWRWWWWKGGK.
.KGKWWWWWWRWWKKGK.
.KGKWRWWWWWWWKAAK.
.KGKWWWWRWWWWKAaK.
..KKWWWWWWWRWKAaK.
...KWWRWWWWWWKAAK.
...KwWWWWWRWwK.K..
...KwWWWWWWWwK....
....KDWWWWWDK.....
""".strip("\n")

BUT_LEGS_STAND = """
....KGGKKGGK......
....KDDK.KDDK.....
.....KK...KK......
""".strip("\n")

BUT_LEGS_A = """
....KGGK.KGGK.....
...KDDK...KDDK....
....KK.....KK.....
""".strip("\n")

BUT_LEGS_B = """
....KGGKKGGK......
...KDDK..KDDK.....
....KK....KK......
""".strip("\n")


def butcher(name, legs, bob):
    save_grid(name, ("." * 18 + "\n") * bob + BUT_TOP + "\n" + legs, BUT_PAL)


butcher("orc_butcher_idle_f0", BUT_LEGS_STAND, 1)
butcher("orc_butcher_idle_f1", BUT_LEGS_STAND, 0)
butcher("orc_butcher_idle_f2", BUT_LEGS_STAND, 0)
butcher("orc_butcher_idle_f3", BUT_LEGS_STAND, 1)
butcher("orc_butcher_run_f0", BUT_LEGS_A, 1)
butcher("orc_butcher_run_f1", BUT_LEGS_STAND, 0)
butcher("orc_butcher_run_f2", BUT_LEGS_B, 1)
butcher("orc_butcher_run_f3", BUT_LEGS_STAND, 0)

# --------------------------------------------------- orc shaman king boss --
# wave-15 boss: robed orc mystic, skull mask, antler crown, orb staff.
SHK_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "P": (96, 60, 130, 255),   # robe purple
    "p": (66, 40, 94, 255),    # robe shade
    "W": (238, 234, 222, 255), # skull mask
    "w": (196, 190, 176, 255), # skull shade
    "G": (110, 152, 62, 255),  # orc hands
    "E": (60, 220, 90, 255),   # glowing eyes / orb
    "e": (26, 130, 60, 255),   # orb shade
    "Y": (226, 180, 62, 255),  # antler crown gold
    "S": (94, 66, 44, 255),    # staff wood
}

SHK_TOP = """
..KY.K......K.YK..
..KYYK......KYYK..
...KYYK....KYYK...
....KYKKKKKKYK....
....KPPPPPPPPK....
...KPWWWWWWWWPK...
...KPWEWWWWEWPK...
...KPWWWWWWWWPK...
...KPWwKWWKwWPK...
....KPWwWWwWPKKE..
....KPPKWWKPPKEeK.
...KPPPPPPPPPKKE..
..KPPPPPPPPPPKSK..
..KGKPPPPPPPPKSK..
..KGKpPPPPPPpKSK..
..KKKpPPPPPPpKSK..
....KpPPPPPPpKSK..
....KPPPPPPPPKSK..
...KPPPPPPPPPPKK..
""".strip("\n")

SHK_LEGS_STAND = """
...KpPPPPPPPPpK...
....KKKKKKKKKK....
""".strip("\n")

SHK_LEGS_A = """
...KpPPPPPPPPpK...
....KKKKKKKKKK....
""".strip("\n")


def shamanking(name, legs, bob):
    save_grid(name, ("." * 18 + "\n") * bob + SHK_TOP + "\n" + legs, SHK_PAL)


shamanking("orc_shamanking_idle_f0", SHK_LEGS_STAND, 1)
shamanking("orc_shamanking_idle_f1", SHK_LEGS_STAND, 0)
shamanking("orc_shamanking_idle_f2", SHK_LEGS_STAND, 0)
shamanking("orc_shamanking_idle_f3", SHK_LEGS_STAND, 1)
shamanking("orc_shamanking_run_f0", SHK_LEGS_A, 1)
shamanking("orc_shamanking_run_f1", SHK_LEGS_STAND, 0)
shamanking("orc_shamanking_run_f2", SHK_LEGS_A, 1)
shamanking("orc_shamanking_run_f3", SHK_LEGS_STAND, 0)

# ------------------------------------------------- berserker recolor -------
# orc_warrior with skin shifted to red + warpaint: an elite variant.


def recolor_to_red(src, dst):
    img = Image.open(src).convert("RGBA")
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            if a and g > r * 1.15 and g > b * 1.15 and g > 70:  # skin pixel
                h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
                h, l, s = 0.99, min(1.0, l * 1.2), min(1.0, s * 1.1)
                r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)
                px[x, y] = (int(r2 * 255), int(g2 * 255), int(b2 * 255), a)
    img.save(dst)


for anim in ("idle", "run"):
    for f in range(4):
        recolor_to_red(
            os.path.join(SPRITES, f"orc_warrior_{anim}_anim_f{f}.png"),
            os.path.join(OUT, f"orc_berserker_{anim}_f{f}.png"),
        )

# ------------------------------------------------------------- weapons -----
WHIP_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "H": (94, 62, 40, 255),    # leather handle
    "h": (128, 90, 56, 255),   # handle light
    "L": (168, 128, 84, 255),  # lash
    "l": (204, 168, 116, 255), # lash light
    "Y": (226, 180, 62, 255),  # gold pommel
}
save_grid("weapon_whip", """
......KKK.......
.....KLlLK......
....KL.KLK......
....KLK.KLK.....
....KLK.KLK.....
....KLLKLK......
.....KLLK.......
......KLK.......
......KhK.......
......KHK.......
......KHK.......
......KYK.......
.......K........
""", WHIP_PAL)

SCYTHE_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "B": (196, 208, 224, 255), # blade
    "b": (124, 138, 160, 255), # blade shade
    "S": (66, 48, 40, 255),    # shaft
    "s": (94, 70, 52, 255),    # shaft light
    "R": (140, 30, 40, 255),   # blood-red wrap
}
save_grid("weapon_scythe", """
..KKKKKK........
.KBBBBBBKK......
.KbbBBBBBBK.....
....KKKbBBK.....
......KsKBK.....
......KSK.K.....
......KsK.......
......KSK.......
......KRK.......
......KSK.......
......KsK.......
......KSK.......
......KsK.......
.......K........
""", SCYTHE_PAL)

# ------------------------------------------------------------- the nun -----
# proper nun: black habit, white coif around the face, gold cross.
NUN_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "B": (40, 36, 48, 255),    # habit black
    "b": (58, 53, 68, 255),    # habit highlight
    "W": (238, 236, 228, 255), # coif white
    "F": (228, 186, 152, 255), # skin
    "f": (198, 152, 120, 255), # skin shade
    "Y": (226, 180, 62, 255),  # gold cross
}

NUN_TOP = """
.....KKKK.....
....KBBBBK....
...KBBBBBBK...
...KBWWWWBK...
...KBWFFWBK...
...KBWFFWBK...
...KBWfFWBK...
....KWFFWK....
....KBWWBK....
...KBBBBBBK...
..KBBBWWBBBK..
..KBBBWYWBBK..
..KBbBBYBBbK..
..KBbBBBBBbK..
...KBBBBBBK...
...KBBBBBBK...
""".strip("\n")

NUN_LEGS_STAND = """
...KBBBBBBK...
....KbKKbK....
....KK..KK....
""".strip("\n")

NUN_LEGS_A = """
...KBBBBBBK...
...KbK..KbK...
...KK....KK...
""".strip("\n")

NUN_LEGS_B = """
...KBBBBBBK...
....KbKKbK....
...KK....KK...
""".strip("\n")


def nun(name, legs, bob):
    save_grid(name, ("." * 14 + "\n") * bob + NUN_TOP + "\n" + legs, NUN_PAL)


nun("nun_idle_f0", NUN_LEGS_STAND, 1)
nun("nun_idle_f1", NUN_LEGS_STAND, 0)
nun("nun_idle_f2", NUN_LEGS_STAND, 0)
nun("nun_idle_f3", NUN_LEGS_STAND, 1)
nun("nun_run_f0", NUN_LEGS_A, 1)
nun("nun_run_f1", NUN_LEGS_STAND, 0)
nun("nun_run_f2", NUN_LEGS_B, 1)
nun("nun_run_f3", NUN_LEGS_STAND, 0)

# --------------------------------------------------------- quasimodo -------
# hunched bell-ringer: hump on the back, head pushed forward, ragged tunic.
QUA_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "D": (58, 44, 34, 255),    # messy hair
    "F": (224, 178, 140, 255), # skin
    "f": (192, 142, 106, 255), # skin shade
    "T": (134, 96, 58, 255),   # tunic
    "t": (100, 70, 44, 255),   # tunic shade
    "R": (146, 42, 40, 255),   # patched sleeve
    "b": (62, 48, 38, 255),    # boots
}

QUA_TOP = """
....KKK.........
..KKTTTKK.......
.KTTTTTTTK......
.KTTTTTTTTKKK...
.KtTTTTTKDDDDK..
.KtTTTTKDDDDDDK.
.KtTTTTKDFFFFDK.
..KTTTTKFFfFFK..
..KTTTTKFFFFK...
..KTTTTTKFFK....
..KRTTTTTTTK....
..KRtTTTTTTK....
...KtTTTTTK.....
""".strip("\n")

QUA_LEGS_STAND = """
...KTTKKTTK.....
....KbK.KbK.....
....KK..KK......
""".strip("\n")

QUA_LEGS_A = """
...KTTK.KTTK....
...KbK...KbK....
...KK.....KK....
""".strip("\n")

QUA_LEGS_B = """
...KTTKKTTK.....
...KbK...KbK....
....KK...KK.....
""".strip("\n")


def quasi(name, legs, bob):
    save_grid(name, ("." * 16 + "\n") * bob + QUA_TOP + "\n" + legs, QUA_PAL)


quasi("quasi_idle_f0", QUA_LEGS_STAND, 1)
quasi("quasi_idle_f1", QUA_LEGS_STAND, 0)
quasi("quasi_idle_f2", QUA_LEGS_STAND, 0)
quasi("quasi_idle_f3", QUA_LEGS_STAND, 1)
quasi("quasi_run_f0", QUA_LEGS_A, 1)
quasi("quasi_run_f1", QUA_LEGS_STAND, 0)
quasi("quasi_run_f2", QUA_LEGS_B, 1)
quasi("quasi_run_f3", QUA_LEGS_STAND, 0)

# ---------------------------------------------------------- assassin -------
# hooded killer: slate hood and mask, only the eyes show, red sash.
ASN_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "H": (56, 62, 80, 255),    # hood
    "h": (78, 86, 108, 255),   # hood light
    "M": (40, 44, 58, 255),    # mask / dark cloth
    "E": (214, 230, 255, 255), # eye slits
    "R": (146, 42, 40, 255),   # sash
    "b": (34, 38, 50, 255),    # boots
}

ASN_TOP = """
.....KKKK.....
....KHHHHK....
...KHHHHHHK...
...KHhhhhHK...
...KHEhhEHK...
...KHMMMMHK...
....KMMMMK....
....KHHHHK....
...KHHHHHHK...
..KHHHHHHHHK..
..KhHHHHHHhK..
..KhHRRRRHhK..
..KKHHHHHHKK..
...KMHHHHMK...
...KMMMMMMK...
""".strip("\n")

ASN_LEGS_STAND = """
...KMMKKMMK...
....KbK.KbK...
....KK...KK...
""".strip("\n")

ASN_LEGS_A = """
...KMMK.KMMK..
...KbK...KbK..
...KK.....KK..
""".strip("\n")

ASN_LEGS_B = """
..KMMK.KMMK...
..KbK...KbK...
...KK...KK....
""".strip("\n")


def assassin(name, legs, bob):
    save_grid(name, ("." * 14 + "\n") * bob + ASN_TOP + "\n" + legs, ASN_PAL)


assassin("assassin_idle_f0", ASN_LEGS_STAND, 1)
assassin("assassin_idle_f1", ASN_LEGS_STAND, 0)
assassin("assassin_idle_f2", ASN_LEGS_STAND, 0)
assassin("assassin_idle_f3", ASN_LEGS_STAND, 1)
assassin("assassin_run_f0", ASN_LEGS_A, 1)
assassin("assassin_run_f1", ASN_LEGS_STAND, 0)
assassin("assassin_run_f2", ASN_LEGS_B, 1)
assassin("assassin_run_f3", ASN_LEGS_STAND, 0)

SHUR_PAL = {
    "K": (24, 18, 26, 255),
    "A": (196, 204, 218, 255),
    "a": (126, 134, 152, 255),
}
save_grid("weapon_shuriken", """
....K....
...KAK...
.K.KaK.K.
KAKaKaKAK
.KaK.KaK.
KAKaKaKAK
.K.KaK.K.
...KAK...
....K....
""", SHUR_PAL)

# ---------------------------------------------------------- molotov --------
MOL_PAL = {
    "K": (24, 18, 26, 255),    # outline
    "R": (238, 130, 32, 255),  # rag flame
    "r": (252, 210, 96, 255),  # flame core
    "W": (222, 214, 196, 255), # rag cloth
    "G": (94, 138, 110, 200),  # green glass
    "g": (66, 104, 82, 220),   # glass shade
    "Y": (206, 142, 38, 255),  # amber liquid
}
save_grid("weapon_molotov", """
...Rr...
...RR...
..KWRK..
..KWK...
..KGgK..
..KGgK..
.KGGGgK.
.KGYYgK.
.KGYYgK.
.KGYYgK.
..KKKK..
""", MOL_PAL)

# ---------------------------------------------------------- ui key icon ----
KEY_PAL = {
    "K": (24, 18, 26, 255),
    "Y": (226, 180, 62, 255),
    "y": (168, 128, 44, 255),
}
save_grid("ui_key", """
.KKKK.......
KYYYYK......
KY..YKKKKKKK
KY..YYYYYYYK
KYYYYKKYKYKK
.KKKK..KyKy.
........K.K.
""", KEY_PAL)

# ---------------------------------------------------------- upgrade card ---
# 44x60 parchment card with gold pixel corners, used by the level-up UI.
card = Image.new("RGBA", (44, 60), (0, 0, 0, 0))
px = card.load()
EDGE = (24, 18, 26, 255)
GOLD = (226, 180, 62, 255)
PAPER = (222, 202, 158, 255)
PAPER2 = (206, 184, 138, 255)
for y in range(60):
    for x in range(44):
        if x in (0, 43) or y in (0, 59):
            px[x, y] = EDGE
        elif x in (1, 42) or y in (1, 58):
            px[x, y] = GOLD
        else:
            px[x, y] = PAPER2 if (x + y) % 7 == 0 else PAPER
for cx, cy in ((3, 3), (38, 3), (3, 54), (38, 54)):
    for dx in range(3):
        for dy in range(3):
            if dx + dy < 3:
                px[cx + dx, cy + dy] = GOLD
card.save(os.path.join(OUT, "card.png"))

print("custom art written:", sorted(os.listdir(OUT)))
